export enum AppConfigAction {
  FETCH_APP_CONFIGURATION = 'FETCH_APP_CONFIGURATION',
  FETCH_APP_CONFIGURATION_COMPLETED = 'FETCH_APP_CONFIGURATION_COMPLETED',
  FETCH_APP_CONFIGURATION_ERROR = 'FETCH_APP_CONFIGURATION_ERROR',
}
