export enum ProductAction {
  FETCH_PRODUCT = 'FETCH_PRODUCT',
  FETCH_PRODUCT_COMPLETED = 'FETCH_PRODUCT_COMPLETED',
  FETCH_PRODUCT_ERROR = 'FETCH_PRODUCT_ERROR',

  UPDATE_PRODUCT = 'UPDATE_PRODUCT',
  UPDATE_PRODUCT_COMPLETED = 'UPDATE_PRODUCT_COMPLETED',
  UPDATE_PRODUCT_ERROR = 'UPDATE_PRODUCT_ERROR',

  SET_SELECTED_PRODUCT = 'SET_SELECTED_PRODUCT',
}
